[package]
name = "noise_for_fun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
insta = "1.34.0"
minifb = "0.25.0"
noise = "0.8.2"
pastel = "0.9.0"
perlin = "0.1.0"
rand = "0.8.5"
